/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doodle_client;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.geom.Line2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.InetAddress;
import java.net.Socket;
import java.util.Stack;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

/**
 *
 * @author Abrar-ThInK_PaD
 */
public class design extends javax.swing.JFrame {

    /**
     * Creates new form design
     */
    static MyThread thread;
       
    public design() {
           
        initComponents();
        
        thread = new MyThread();
         thread.setDaemon(true);
         thread.start();
          ObjectInputStream fin = null ;
          try {
               fin = new ObjectInputStream(new FileInputStream("Client_Lineinfo.txt"));
            
            } catch (Exception ex) {
               // Logger.getLogger(design.class.getName()).log(Level.SEVERE, null, ex);
            }
          Graphics g = canvas.getGraphics();
          while(true){
                 
                 try{ 
                     
                  Line1 l =  (Line1)fin.readObject();    
                  thread.list.add(l);
                 // g.setColor(jchooser.getColor());
                 // g.drawLine(l.start_x, l.start_y, l.end_x,l.end_y);
                  
                    g.setColor(new Color(l.r,l.g,l.b));
                    Graphics2D g2 = (Graphics2D) g;
                    g2.setStroke(new BasicStroke(l.strokesize));
                    g2.draw(new Line2D.Float(l.start_x,l.start_y,l.end_x,l.end_y));
                 }
                 catch(Exception e)
                 {
                  break;   
                 }
                  
              }      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas = new java.awt.Canvas();
        jchooser = new javax.swing.JColorChooser();
        SaveButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        chatBox = new java.awt.TextArea();
        chatSend = new java.awt.TextField();
        SendButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        SizeSlider = new javax.swing.JSlider();
        ClearButton = new javax.swing.JButton();
        ChatClearButton = new javax.swing.JButton();
        SizeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doodle_Messenger Cilent");
        setResizable(false);
        setSize(new java.awt.Dimension(920, 600));

        canvas.setBackground(new java.awt.Color(255, 255, 255));
        canvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canvasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                canvasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                canvasMouseReleased(evt);
            }
        });
        canvas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                canvasComponentShown(evt);
            }
        });
        canvas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                canvasMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                canvasMouseMoved(evt);
            }
        });

        jchooser.setPreviewPanel(new JPanel());
        jchooser.setColor(new java.awt.Color(0, 0, 0));
        jchooser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        chatBox.setEditable(false);

        chatSend.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        chatSend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chatSendKeyPressed(evt);
            }
        });

        SendButton1.setText("Send ");
        SendButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButton1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(153, 153, 153));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField2.setText("         Chat");
        jTextField2.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SendButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addComponent(chatBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chatSend, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chatBox, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chatSend, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SendButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SizeSlider.setMajorTickSpacing(5);
        SizeSlider.setMaximum(20);
        SizeSlider.setMinorTickSpacing(1);
        SizeSlider.setPaintTicks(true);
        SizeSlider.setValue(0);
        SizeSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SizeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SizeSliderStateChanged(evt);
            }
        });

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        ChatClearButton.setText("ClearChat");
        ChatClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChatClearButtonActionPerformed(evt);
            }
        });

        SizeLabel.setText("    Size : 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jchooser, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(SizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ChatClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvas, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ChatClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jchooser, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvas, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 static Socket s;
    int px=0,py=0;
boolean f = false,rubber = false;
static ObjectInputStream in,cin;
    static ObjectOutputStream ou,cou;
static Com p;
 boolean rel = false; 
  boolean press = false;
    private void canvasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseDragged
       
        
    press = false;
     
        if(f==true&&rubber==false) {
         Graphics g = canvas.getGraphics();
         int value = SizeSlider.getValue();
         g.setColor(jchooser.getColor());
         Graphics2D g2 = (Graphics2D) g;
         g2.setStroke(new BasicStroke(value));
         g2.draw(new Line2D.Float(px, py, evt.getX(), evt.getY())); 
          
        //new_code_start
        Line1 line = new Line1();  
        line.start_x = px;
        line.start_y = py;
        line.end_x=evt.getX();
        line.end_y=evt.getY();
        line.strokesize = value;
        line.r = jchooser.getColor().getRed();
        line.g = jchooser.getColor().getGreen();
        line.b = jchooser.getColor().getBlue();
        
        thread.list.add(line);  
         //new_code_end   
           
       
           
        p.x = evt.getX();
        p.y = evt.getY();
        p.f = press;
        p.r = jchooser.getColor().getRed();
        p.g = jchooser.getColor().getGreen();
        p.b = jchooser.getColor().getBlue();
        p.msg = chatSend.getText();
        p.send_flag = false;
        p.sendstrokesize = SizeSlider.getValue();
           try {
               p.writeObject(ou);
           } catch (Exception ex) {
               //Logger.getLogger(design.class.getName()).log(Level.SEVERE, null, ex);
           }
         
         
            
        px = evt.getX();
        py = evt.getY(); 
        
        }    
       
    }//GEN-LAST:event_canvasMouseDragged
  
    private void canvasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseClicked
      
 
    }//GEN-LAST:event_canvasMouseClicked
   
    private void canvasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseReleased
        f = false; 
       Graphics g = canvas.getGraphics();
       
      press = false;
        
    }//GEN-LAST:event_canvasMouseReleased
   
    private void canvasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMousePressed
       Graphics g = canvas.getGraphics();
        press = true;
        p.x = evt.getX();
        p.y = evt.getY();
        p.f = press;
        p.r = jchooser.getColor().getRed();
        p.g = jchooser.getColor().getGreen();
        p.b = jchooser.getColor().getBlue();
        p.msg = chatSend.getText();
        p.send_flag = false;
        p.sendstrokesize = SizeSlider.getValue();
           try {
               p.writeObject(ou);
           } catch (Exception ex) {
               //Logger.getLogger(design.class.getName()).log(Level.SEVERE, null, ex);
           }
       
        px = evt.getX();
        py = evt.getY();
        f = true;
        press = true;
        
        int value = SizeSlider.getValue();
        
         g.setColor(jchooser.getColor());
         Graphics2D g2 = (Graphics2D) g;
         g2.setStroke(new BasicStroke(value));
         g2.draw(new Line2D.Float(px, py, evt.getX(), evt.getY())); 
        //new_code_start
        Line1 line = new Line1();  
        line.start_x = px;
        line.start_y = py;
        line.end_x= px;
        line.end_y=py;
        line.strokesize = value;
        line.r = jchooser.getColor().getRed();
        line.g = jchooser.getColor().getGreen();
        line.b = jchooser.getColor().getBlue();
        
        thread.list.add(line);  
         //new_code_end   
        
        
         //g.drawImage(img, 0, 0, canvas.getWidth(), canvas.getHeight(), null);
        
    }//GEN-LAST:event_canvasMousePressed
 


    
    private void canvasComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_canvasComponentShown
       
    }//GEN-LAST:event_canvasComponentShown
  int prex,prey;
  
    private void canvasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseMoved
        // TODO add your handling code here:
       
    }//GEN-LAST:event_canvasMouseMoved

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed

         try {
           ObjectOutputStream fou = new ObjectOutputStream(new FileOutputStream("Client_Lineinfo.txt"));
           for(Line1 l : thread.list) 
           {
               fou.writeObject(l);
               
           }
           
           
       } catch (Exception ex) {
          // Logger.getLogger(design.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void SendButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButton1ActionPerformed
       
         
             //System.out.println(chatSend.getText());
        String s = chatSend.getText();
      try{
        char c = s.charAt(0);
      }
      catch(StringIndexOutOfBoundsException e){
          return;
      }
        p.x =0;
        p.y = 0;
        p.f = false;
        p.r = jchooser.getColor().getRed();
        p.g = jchooser.getColor().getGreen();
        p.b = jchooser.getColor().getBlue();
        p.msg = chatSend.getText();
       p.send_flag = true;
       p.sendstrokesize = 0;
        try {
            p.writeObject(ou);
            chatBox.append("Client: ");
              chatBox.append(chatSend.getText());
              chatBox.append("\n"); 
              chatSend.setText(null);
        } catch (Exception ex) {
           // Logger.getLogger(design.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_SendButton1ActionPerformed

    private void chatSendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chatSendKeyPressed
        // TODO add your handling code here:
        if(  evt.getKeyChar()=='\n' ) 
      {   
         
          java.awt.event.ActionEvent evt1 = null;
          SendButton1ActionPerformed(evt1);
          }
    
    }//GEN-LAST:event_chatSendKeyPressed

    private void SizeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SizeSliderStateChanged
       int value = SizeSlider.getValue();
      //  String add = Integer.toString(value);
        System.out.println(value);
        SizeLabel.setText("    Size : "+value );
        
    }//GEN-LAST:event_SizeSliderStateChanged

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        canvas.repaint();
        thread.list.clear();

    }//GEN-LAST:event_ClearButtonActionPerformed

    private void ChatClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChatClearButtonActionPerformed
        // TODO add your handling code here:
        chatBox.setText(null);
    }//GEN-LAST:event_ChatClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                
                try{
                    
                    Thread.sleep(4500);
                }
                catch(Exception e){
                    
                }
                
                new design().setVisible(true);
            }
        });
        try{
            String ip = "localhost";
           s = new Socket(InetAddress.getByName(ip),500);
           ou = new ObjectOutputStream(s.getOutputStream());
           in = new ObjectInputStream(s.getInputStream());
           
           //cou = new ObjectOutputStream(s.getOutputStream());
           //cin = new ObjectInputStream(s.getInputStream());
           
           p = new Com();
           //ou.flush();
           
           int ppx=0,ppy=0;
          while(true)
          {
             
            p.readObject(in);
           
          if(p.send_flag)  
          {
             // chatBox.setText(p.msg); 
              chatBox.append("Server: ");
              chatBox.append(p.msg);
              chatBox.append("\n");
          }
         else
          {
              
          
            if(p.f==true)
            {
             ppx = p.x;
             ppy = p.y;
            }
            Graphics g = canvas.getGraphics();
             
            //g.setColor(new Color(p.r,p.g,p.b));
            //g.drawLine(ppx,ppy,p.x,p.y); 
            g.setColor(new Color(p.r,p.g,p.b));
         Graphics2D g2 = (Graphics2D) g;
         g2.setStroke(new BasicStroke(p.sendstrokesize));
         g2.draw(new Line2D.Float(ppx,ppy,p.x,p.y)); 
            
        Line1 line = new Line1();  
        line.start_x = ppx;
        line.start_y = ppy;
        line.end_x= p.x;
        line.end_y=p.y;
        line.strokesize = p.sendstrokesize;
        line.r = p.r;
        line.g = p.g;
        line.b = p.b;
        
        thread.list.add(line);  
           
           ppx = p.x;
           ppy = p.y;
          }
          }
        }
        catch(Exception e)
        {
            
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChatClearButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton SendButton1;
    private javax.swing.JLabel SizeLabel;
    private javax.swing.JSlider SizeSlider;
    public static java.awt.Canvas canvas;
    private static java.awt.TextArea chatBox;
    private java.awt.TextField chatSend;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JColorChooser jchooser;
    // End of variables declaration//GEN-END:variables
}
